### ISSUE TITLE
[Proposal] ->toEqualOneOf() matcher

### ISSUE THREAD

**Issue by tyranron** [kahlan/extra-matcher#1]
Continuing [kahlan#170](https://github.com/kahlan/kahlan/issues/170) thread...

> In regards of `->toEqualOneOf()` it doesn't seem to be appropriate to the "enum" use case. Anyway if you feel like it also has some valid usage, feel free to add it there.

I think we need it just to be closer to existing matchers design. We have `->toBe()` that acts as `===` and `->toEqual()` that acts like `==`.
So `->toBeOneOf()` acts like `in_array(actual, [expected], true)` which corresponds `->toBe()` semantic. And `->toEqualOneOf()` just for corresponding `->toEqual()` semantic (`in_array(actual, [expected], false)`).

I understand that case

``` php
expect("1")->toEqualOneOf([1, 2, 3]);
```

is sort of anti-pattern and better not allow such situations.
But, definitely, there are situations where developer cannot choose much, and `->toEqualOneOf()` can be quite handy and more understandable instead bunch of `expect((int)"1")->toBeOneOf([1, 2, 3])` cases.

Would like to hear more opinions...

**Comment by samsonasik** [comment]
interesting, I've created PR #2 for it ;)

**Comment by jails** [comment]
Makes sense :+1:

**Comment by samsonasik** [comment]
implemented in https://github.com/kahlan/extra-matcher/commit/7c384e40a20c230c0fd287c438c2c8e029b3aca9
